<h1>Регистраторы</h1>
<p class="edit_form_title"><img src="/DHO/images/plus.png" onclick="showForm(0,70,'#recorderAdd','#content');" class="action">  Добавить нового регистратора</p>
<div id="recorderAdd0" class="edit_form">
          <form id="recorderAF<?php echo $recorder['recorder_id'];?>" method="post" action="/DHO/modules/recorder/module.php?action=add">
            <table class="tab">
                <tr><td>Название</td><td>Логин</td><td>Пароль</td><td><span onclick="hideForm(0,'#recorderAdd');" class="hide_edit_form">-</span></td></tr>
                <tr><td><input type="text" name="name" value=""></td><td><input type="text" name="login" value=""></td><td><input type="text" name="pass" value=""><td><button type="submit" class="button">Сохранить</button></td></tr>
               
            </table>
      </form>
      </div>