<div id="owner<?php echo $owner['owner_id'];?>" class="owner">
    <table class="tab">
        <?php  if($owner['first']==1):?>
        <tr><td>Имя, фамилия </td><td>Адреса электронной почты</td><td colspan="2">Номера телефонов</td></tr>
        <?php endif;?>
    <?php 
       echo'<tr><td>'.$owner['firstname'].' '.$owner['lastname'].'</td>';
       echo'<td><div class="listbox">';
            foreach ($owner['emails'] as $email) {
                echo $email['email'].'<br>';
            }
            echo'</div></td><td><div class="listbox">';
            foreach ($owner['phones'] as $phone) {
               echo $phone['phone'].'<br>';
                
            }
      echo'</div>';
      ?></td><td><img src="images/pencil.png" width="20" height="20" onclick="showForm(<?php echo $owner['owner_id'];?>,240,'#ownerEdit','#owner<?php echo $owner['owner_id'];?>');" class="action">&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp<img src="/DHO/images/del_cross.png" class="action" onClick="deleteObject(<?php echo $owner['owner_id'];?>,'owner');"></td></tr><tr><td colspan="4">
          
      <div id="ownerEdit<?php echo $owner['owner_id'];?>" class="edit_form">
          <p class="edit_form_title">Редактрование данных владельца</p>
         <form id="ownerEF<?php echo $owner['owner_id'];?>" method="post" action="/DHO/modules/owner/module.php?action=edit">
            <input type="hidden" value="<?php echo $owner['owner_id'];?>" name="owner_id">
            <table class="tab">
                <tr><td>Имя</td><td><input type="text" name="firstname" value="<?php echo $owner['firstname'];?>"></td><td><span onclick="hideForm(<?php echo $owner['owner_id'];?>,'#ownerEdit');" class="hide_edit_form">-</span></td></tr>
                <tr><td>Фамилия</td><td><input type="text" name="lastname" value="<?php echo $owner['lastname'];?>"></td></tr>
                <tr><td colspan="3">Адреса электронной почты</td></tr>
                <tr>
                   <?php
                       echo'<td><input type="hidden" name="emailId0" value="'.$owner['emails'][0]['id'].'"><input type="text" name="email0" value="'.$owner['emails'][0]['email'].'"></td>';
                       echo'<td><input type="hidden" name="emailId1" value="'.$owner['emails'][1]['id'].'"><input type="text" name="email1" value="'.$owner['emails'][1]['email'].'"></td>';
                       echo'<td><input type="hidden" name="emailId2" value="'.$owner['emails'][2]['id'].'"><input type="text" name="email2" value="'.$owner['emails'][2]['email'].'"></td>';
                   
                   
                   ?>
                </tr>
                 <tr><td colspan="3">Номера телефонов</td></tr>
                <tr>
                   <?php
                       echo'<td><input type="hidden" name="phoneId0" value="'.$owner['phones'][0]['id'].'"><input id="phone" type="text" name="phone0" value="'.$owner['phones'][0]['phone'].'"></td>';
                       echo'<td><input type="hidden" name="phoneId1" value="'.$owner['phones'][1]['id'].'"><input id="phone" type="text" name="phone1" value="'.$owner['phones'][1]['phone'].'"></td>';
                       echo'<td><input type="hidden" name="phoneId2" value="'.$owner['phones'][2]['id'].'"><input id="phone" type="text" name="phone2" value="'.$owner['phones'][2]['phone'].'"></td>';
                   
                   ?>
                </tr>
                <tr><td colspan="4"><button type="submit" class="button">Сохранить</button></td></tr>
            </table>
      </form>
      </div> </td></tr>
    </table>
    
    
    
  </div> 